# Generated by Django 4.2.2 on 2023-06-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_color', models.CharField(max_length=200)),
                ('product_size', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.CharField(max_length=200)),
                ('prod_image', models.ImageField(upload_to='cards/')),
                ('currency', models.CharField(max_length=25)),
                ('account', models.CharField(max_length=200)),
                ('user_first_name', models.CharField(max_length=200)),
                ('user_second_name', models.CharField(max_length=200)),
                ('time_Added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
