# Generated by Django 4.0.4 on 2022-10-16 10:31

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('global_category_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_category', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=200)),
                ('Factory_Name', models.CharField(max_length=100)),
                ('Model_Name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('EGP', 'EGP'), ('$', '$')], default='EGP', max_length=200)),
                ('last_price_this_product_added', models.CharField(default='0', max_length=20)),
                ('Quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55'), ('60', '60'), ('65', '65'), ('70', '70'), ('75', '75'), ('80', '80'), ('85', '85'), ('90', '90'), ('95', '95'), ('100', '100')], default='1', max_length=200)),
                ('time_Added', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('color', multiselectfield.db.fields.MultiSelectField(choices=[('0', '0'), ('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White')], default='0', max_length=28)),
                ('size_of_clothes', multiselectfield.db.fields.MultiSelectField(choices=[('0', '0'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='0', max_length=22)),
                ('weight_of_the_product', models.CharField(max_length=25)),
                ('weight_of_the_product_select_type', models.CharField(choices=[('Gram', 'Gram'), ('Kilogram', 'Kilogram')], max_length=25)),
                ('Package_Dimensions', models.CharField(max_length=100)),
                ('Number_of_review', models.IntegerField(default=0)),
                ('brief_description', models.CharField(max_length=200)),
                ('Full_description', models.TextField()),
                ('information', models.TextField()),
                ('product_serial_number', models.CharField(max_length=255)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_category_home.global_category')),
            ],
            options={
                'unique_together': {('child_category', 'product_name')},
            },
        ),
    ]
