# Generated by Django 4.0.4 on 2022-10-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='img',
            new_name='main_img',
        ),
        migrations.AddField(
            model_name='products',
            name='img_list_1',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='img_list_2',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='img_list_3',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='img_list_4',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='img_list_5',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
