# Generated by Django 4.0.4 on 2022-09-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Number_of_review',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
