# Generated by Django 4.0.4 on 2022-10-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_number_of_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Number_of_review',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
