# Generated by Django 4.0.4 on 2022-10-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_number_of_review_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(choices=[('0', '0'), ('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White')], default='0', max_length=200),
        ),
    ]
