# Generated by Django 4.0.4 on 2022-10-04 21:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size_of_clothes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', '0'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='0', max_length=22),
        ),
    ]
