# Generated by Django 4.0.4 on 2022-10-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('F_Name', models.CharField(max_length=255)),
                ('L_Name', models.CharField(max_length=255)),
                ('Account', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('profile_image', models.ImageField(upload_to='account/')),
                ('Password', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Mobile_Number', models.CharField(max_length=255)),
                ('Address_1', models.CharField(max_length=255)),
                ('Address_2', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('Zip_Code', models.CharField(max_length=255)),
                ('Role', models.CharField(default='Client', max_length=255)),
            ],
        ),
    ]
