# Generated by Django 4.0.4 on 2022-09-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(max_length=255)),
                ('account_image', models.CharField(max_length=255)),
                ('f_name', models.CharField(max_length=255)),
                ('client_message', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=255)),
                ('child_category', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('client_foreign_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'unique_together': {('account', 'category_name', 'child_category', 'product_name')},
            },
        ),
    ]
