# Generated by Django 4.0.4 on 2022-09-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=200)),
                ('Account', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=255)),
                ('Message', models.TextField()),
            ],
        ),
    ]
