# Generated by Django 4.2.2 on 2023-06-10 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='global_category',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Image_random', models.ImageField(upload_to='images/Image_random/')),
                ('small_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_precent', models.CharField(choices=[('15%', '15%'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], max_length=50)),
                ('Image_discount', models.ImageField(upload_to='images/discounts/')),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_category_home.global_category')),
            ],
        ),
        migrations.CreateModel(
            name='category_images_for_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_images', models.ImageField(upload_to='images/category_images_for_home/')),
                ('small_brief_text', models.TextField()),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_category_home.global_category')),
            ],
        ),
    ]
