# Generated by Django 4.2.2 on 2023-06-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lots_Sponser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_sp', models.ImageField(upload_to='sponser_lots_img/From_DB/')),
                ('time_Added', models.DateTimeField(auto_now_add=True)),
                ('Brief_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sponser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_sp', models.ImageField(upload_to='sponser_image/')),
                ('time_Added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
